### PR TITLE
Added optimization for copying arrays of simple types from python to C using buffer protocol (backport #129)

### PR DESCRIPTION
**Pull request by hexonxons**
Backport https://github.com/ros2/rosidl_python/pull/129 to foxy

Related to #135

### CODE REVIEW

**Comment by hexonxons** [comment]
@clalancette @sloretz Hello
Is there any chance of this being merged and released to foxy along with messages packages?

**Comment by karl-schulz** [comment]
I want to add that we used this fix multiple months with foxy without issues on multiple machines. I think it would be good to have it in there for the large foxy userbase.

**Comment by sloretz** [comment]
CI
* Repos: `https://gist.githubusercontent.com/sloretz/0ceeab3a1c8560ca5224fd213f672834/raw/345910333b79c1566f0bc5eb2cf99c2cb18f40e4/ros2.repos`
* build: `--packages-above-and-dependencies rosidl_generator_py`
* test: `--packages-above rosidl_generator_py`


Jobs
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15656/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10334/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13322/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15877/)

**Review by sloretz — APPROVED** [review]
LGTM with green CI

**Comment by aprotyas** [comment]
The test failures look unrelated, but kicking off CI again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15705/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10385/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13372/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15945/)

**Comment by aprotyas** [comment]
Looks like the failing `sros2` tests have been ticketed in https://github.com/ros2/sros2/issues/251.

**Comment by sloretz** [comment]
I'm not sure about some of the test failures on the Windows CI, so here's two more runs

* Rerun Windows: [Build Status](https://ci.ros2.org/job/ci_windows/16014/)
* Foxy unchanged on Windows for comparison [Build Status](https://ci.ros2.org/job/ci_windows/16015/)

**Comment by sloretz** [comment]
Only Windows test failure in the rerun that's not in the pure-Foxy CI is:

https://ci.ros2.org/job/ci_windows/16014/testReport/junit/ros2doctor.test/test_cli/test_cli/

Taking a closer look now

**Comment by sloretz** [comment]
Looks like the ros2doctor test is known flaky, and was fixed in https://github.com/ros2/ros2cli/pull/521 but not backported to Foxy

**Comment by sloretz** [comment]
CI LGTM Thanks for the PR!

**Pull request merged**
