### PR TITLE
remove python_cmake_module as it has been migrated to its own repository

### PR DESCRIPTION
**Pull request by wjwwood**
See the new repository here: https://github.com/ros2/python_cmake_module

https://github.com/ros2/ros2/pull/781 is also required.

### CODE REVIEW

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8170/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4151/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6654/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8049/)

**Comment by nuclearsandwich** [comment]
It looks like CI is iterating on the package names before checking out the test branch which is causing failures due to the duplicate package name.

**Comment by wjwwood** [comment]
Actually I had the wrong repository in place in the ros2/ros2 pr. New CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8171/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4152/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6655/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8050/)

**Comment by wjwwood** [comment]
Mistakes were made, this one should work hopefully:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8177/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4156/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6659/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8054/)

**Pull request merged**
