### PR TITLE
Change decode mode into replace.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rclpy/issues/881

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos could you do review when you have time?

**Review by iuhilnehc-ynos — APPROVED** [review]
LGTM.

**Comment by fujitatomoya** [comment]
@clalancette CI is unstable, are we having any problems on CI?

**Comment by iuhilnehc-ynos** [comment]
@fujitatomoya 

I think @clalancette had already fixed it in this PR(https://github.com/ros2/ci/pull/677).

**Comment by fujitatomoya** [comment]
CI retry:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17084/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11637/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17505/)

**Review by jacobperron — APPROVED** [review]
I think this is reasonable. It makes the behavior more consistent between subscriptions in rclcpp and rclpy.

**Comment by fujitatomoya** [comment]
@Mergifyio backport humble galactic foxy

**Pull request merged**
